# Generated by Django 4.2.13 on 2024-10-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
