# Generated by Django 4.2.13 on 2024-10-11 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stockapp', '0002_alter_livreur_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='livreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stockapp.livreur'),
        ),
    ]
