# Generated by Django 4.2.13 on 2024-10-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockapp', '0003_vente_livreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='whatsapp',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
